### ISSUE TITLE
Unsecure hasching 

### ISSUE THREAD

**Issue by florian-sabonchi** [RaxoCoding/PythonPasswordVault#1]
def hashPassword(input):
    hash1 = hashlib.md5(input)
    hash1 = hash1.hexdigest()

    return hash1

md5 is not a secure hashing allgorithm

**Comment by RaxoCoding** [comment]
fixed

**Comment by florian-sabonchi** [comment]
Sha256 also not recommended for password hasing
https://security.stackexchange.com/questions/195563/why-is-sha-256-not-good-for-passwords#195565
